# DROP DATABASE `shm`;
# DROP DATABASE [IF EXISTS] `shm`;
DROP DATABASE IF EXISTS `shm`;

# CREATE DATABASE `shm`;
# CREATE DATABASE [IF NOT EXISTS] `shm`;
# CREATE DATABASE [IF NOT EXISTS] `shm` [DEFAULT] CHARACTER SET [=] 'utf8mb4' [DEFAULT] COLLATE [=] 'utf8mb4_general_ci';
# CREATE DATABASE [IF NOT EXISTS] `shm` [DEFAULT] CHARSET [=] 'utf8mb4' [DEFAULT] COLLATE [=] 'utf8mb4_general_ci';
# CREATE DATABASE IF NOT EXISTS `shm` DEFAULT CHARSET = 'utf8mb4' DEFAULT COLLATE = 'utf8mb4_general_ci';
CREATE DATABASE IF NOT EXISTS `shm` DEFAULT CHARSET = 'utf8' DEFAULT COLLATE = 'utf8_general_ci';


